name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3  # Atualizado para a versão mais recente

      - name: Configurar o Terraform
        uses: hashicorp/setup-terraform@v2  # Versão compatível com Node.js 20
        with:
          terraform_version: 1.1.6

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2  # Atualizado para a versão mais recente
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Ajuste para a região que você está usando

      - name: Inicializar o Terraform
        run: terraform init

      - name: Aplicar o Terraform
        run: terraform apply -auto-approve

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Conectar e Verificar a Página
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_private_key
          chmod 600 /tmp/ssh_private_key
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_private_key ubuntu@${{ env.SERVER_IP }} << 'EOF'
          curl http://localhost
          EOF
